apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.component_id }}-jump-app
  annotations:
    argocd/app-name: ${{ values.component_id }}-jump-app
    backstage.io/kubernetes-id: ${{values.component_id}}
    backstage.io/kubernetes-namespace: ${{ values.ocp_namespace }}
    backstage.io/source-location: url:${{ values.gitops_repo_files }}
    backstage.io/techdocs-ref: url:${{ values.gitops_repo_files }}
  tags:
    - microservices
    - jumpapp
spec:
  type: service
  lifecycle: production
  owner: user:default/guest