apiVersion: v1
kind: Secret
metadata:
  name: argocd-basic-auth
  namespace: backstage
type: Opaque
data:
  username: YWRtaW4K
  password: cGFzc3dvcmQK
  url: aHR0cHM6Ly9vcGVuc2hpZnQtZ2l0b3BzLXNlcnZlci1vcGVuc2hpZnQtZ2l0b3BzLmFwcHMuYWNpZG9ucGUxMDEuc2FuZGJveDQ3MC5vcGVudGxjLmNvbQo=